### ISSUE TITLE
run ./script-simple.sh @caffe-lstm/example/deep-activity-rec/ibrahim16-cvpr-simple report error 

### ISSUE THREAD

**Issue by qdinfish** [mostafa-saad/deep-activity-rec#8]
Hi Mostafa,

I encounter following issue when run the installation guide you wrote.  

run ./script-simple.sh 
exePhase1_2:error while loading shared libraries: libcaffe.so : cannot open shared object file: no such file or directory 

Thanks a lot,
Jc

**Comment by jichaoliu** [comment]
START processing script ./script-simple.sh
OUTPUT Directory is  /home/c303/teacher/liujichao/caffe-lstm/examples/deep-activity-rec/ibrahim16-cvpr-simple

Doing path VALIDATIONS
READY...STEADY...Gooo ?

------------------------------------------------------
Phase 1 - Generating Network 1 Data - /home/c303/teacher/liujichao/caffe-lstm/examples/deep-activity-rec/ibrahim16-cvpr-simple/p1-network1
/home/c303/teacher/liujichao/caffe-lstm/examples/deep-activity-rec/exePhase1_2: error while loading shared libraries: libcaffe.so: cannot open shared object file: No such file or directory
========================
Phase 1 - B - Computing Mean of Network 1 Training Data - /home/c303/teacher/liujichao/caffe-lstm/examples/deep-activity-rec/ibrahim16-cvpr-simple/p1-network1
Computing image mean for trainval dataset:  examples/deep-activity-rec/ibrahim16-cvpr-simple/p1-network1
F0221 17:41:23.428210  9822 db_leveldb.cpp:16] Check failed: status.ok() Failed to open leveldb examples/deep-activity-rec/ibrahim16-cvpr-simple/p1-network1/trainval-leveldb
Invalid argument: examples/deep-activity-rec/ibrahim16-cvpr-simple/p1-network1/trainval-leveldb: does not exist (create_if_missing is false)
*** Check failure stack trace: ***
    @     0x7f8978111daa  (unknown)
    @     0x7f8978111ce4  (unknown)
    @     0x7f89781116e6  (unknown)
    @     0x7f8978114687  (unknown)
    @     0x7f89785d3dfa  caffe::db::LevelDB::Open()
    @           0x4019c8  main
    @     0x7f8977321f45  (unknown)
    @           0x4024c1  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)
Done.
========================
Phase 1 - C - Network 1 Training
Running Caffe using GPU In Directory  examples/deep-activity-rec/ibrahim16-cvpr-simple/p1-network1
------------------------------------------------------
Phase 2 - A - Generating Data to be Fused - /home/c303/teacher/liujichao/caffe-lstm/examples/deep-activity-rec/ibrahim16-cvpr-simple/p2-ready-fuse
/home/c303/teacher/liujichao/caffe-lstm/examples/deep-activity-rec/exePhase1_2: error while loading shared libraries: libcaffe.so: cannot open shared object file: No such file or directory
========================
Phase 2 - B - Creating Mean File of Fused Data
Computing image mean for dataset:  trainval
F0221 17:41:44.583369  9841 db_leveldb.cpp:16] Check failed: status.ok() Failed to open leveldb /home/c303/teacher/liujichao/caffe-lstm/examples/deep-activity-rec/ibrahim16-cvpr-simple/p2-ready-fuse/trainval-leveldb
Invalid argument: /home/c303/teacher/liujichao/caffe-lstm/examples/deep-activity-rec/ibrahim16-cvpr-simple/p2-ready-fuse/trainval-leveldb: does not exist (create_if_missing is false)
*** Check failure stack trace: ***
    @     0x7f804a122daa  (unknown)
    @     0x7f804a122ce4  (unknown)
    @     0x7f804a1226e6  (unknown)
    @     0x7f804a125687  (unknown)
    @     0x7f804a5e4dfa  caffe::db::LevelDB::Open()
    @           0x4019c8  main
    @     0x7f8049332f45  (unknown)
    @           0x4024c1  (unknown)
    @              (nil)  (unknown)
./script-simple.sh: line 142:  9841 Aborted                 (core dumped) $CAFFE/build/tools/compute_image_mean -backend=leveldb $NETWORK2_LEVELDB_FUSION_DIR/$TRAIN_SRC-leveldb $NETWORK2_LEVELDB_FUSION_DIR/mean.binaryproto
------------------------------------------------------
Phase 3 - Generarting LSTM 2 Data - /home/c303/teacher/liujichao/caffe-lstm/examples/deep-activity-rec/ibrahim16-cvpr-simple/p4-network2
/home/c303/teacher/liujichao/caffe-lstm/examples/deep-activity-rec/exePhase3: error while loading shared libraries: libcaffe.so: cannot open shared object file: No such file or directory
------------------------------------------------------
Phase 4 - A - LSTM 2 Training - /home/c303/teacher/liujichao/caffe-lstm/examples/deep-activity-rec/ibrahim16-cvpr-simple/p4-network2
Running Caffe using GPU In Directory  examples/deep-activity-rec/ibrahim16-cvpr-simple/p4-network2
========================
Phase 4 - B - Temporal Evaluation
examples/deep-activity-rec/exePhase4: error while loading shared libraries: libcaffe.so: cannot open shared object file: No such file or directory
------------------------------------------------------

DONE processing script ./script-simple.sh











root@c303-Default-string:/home/c303/teacher/liujichao/caffe-lstm/examples/deep-activity-rec/ibrahim16-cvpr-simple# ./script-clean.sh 
rm: cannot remove ‘examples/deep-activity-rec/ibrahim16-cvpr-simple/p1-network1/test-leveldb’: No such file or directory
rm: cannot remove ‘examples/deep-activity-rec/ibrahim16-cvpr-simple/p1-network1/trainval-leveldb’: No such file or directory
rm: cannot remove ‘examples/deep-activity-rec/ibrahim16-cvpr-simple/p1-network1/mean.binaryproto’: No such file or directory
rm: cannot remove ‘examples/deep-activity-rec/ibrahim16-cvpr-simple/p1-network1/z_log_dataset_net1.txt’: No such file or directory
rm: cannot remove ‘examples/deep-activity-rec/ibrahim16-cvpr-simple/p1-network1/z_trainval-test-log.txt’: No such file or directory
rm: cannot remove ‘examples/deep-activity-rec/ibrahim16-cvpr-simple/p1-network1/z_snapshot_iter_*.caffemodel’: No such file or directory
rm: cannot remove ‘examples/deep-activity-rec/ibrahim16-cvpr-simple/p1-network1/z_snapshot_iter_*.solverstate’: No such file or directory
rm: cannot remove ‘examples/deep-activity-rec/ibrahim16-cvpr-simple/p2-ready-fuse’: No such file or directory
rm: cannot remove ‘examples/deep-activity-rec/ibrahim16-cvpr-simple/p4-network2/test-leveldb’: No such file or directory
rm: cannot remove ‘examples/deep-activity-rec/ibrahim16-cvpr-simple/p4-network2/trainval-leveldb’: No such file or directory
rm: cannot remove ‘examples/deep-activity-rec/ibrahim16-cvpr-simple/p4-network2/z_log_dataset_net2.txt’: No such file or directory
rm: cannot remove ‘examples/deep-activity-rec/ibrahim16-cvpr-simple/p4-network2/z_trainval-test-log.txt’: No such file or directory
rm: cannot remove ‘examples/deep-activity-rec/ibrahim16-cvpr-simple/p4-network2/z_trainval-test-window-evaluation-log-prop.txt’: No such file or directory
rm: cannot remove ‘examples/deep-activity-rec/ibrahim16-cvpr-simple/p4-network2/z_snapshot_iter_*.caffemodel’: No such file or directory
rm: cannot remove ‘examples/deep-activity-rec/ibrahim16-cvpr-simple/p4-network2/z_snapshot_iter_*.solverstate’: No such file or directory

**Comment by mostafa-saad** [comment]
Hello,

I think, this should be a problem on your side. The environment where you run is not prepared to see Caffe or even it is not setup correctly (e.g. make sure caffe.so exist). Please Google web for such error or Caffe groups to see the problem.

**Comment by qdinfish** [comment]
Mostafa，
Thanks for your quick response.
i only do "make all" in your directory ,and I also need do it in the@caffe-Lstm directory, right?
I'm a new one for caffe.
Thanks a lot,
Jc

**Comment by mostafa-saad** [comment]
Kindly read on Caffe website for caffe installations. Typically it is annoying to get all things correct from face time. You know caffe is installed when caffe.so exists in the build dir.

**Comment by jichaoliu** [comment]
Hi Mostafa,

I fixed above issue from google and encounter below issue， I have 2 questions.

1: LD_LIBRARY_PATH pointing to LSTM implementation
Where is the LSTM implementation ? I set LD_LIBRARY_PATH pointing to /home/caffe-lstm/build/examples/lstm_sequence, right?

2. Do you know the issue 
symbol lookup error: examples/deep-activity-rec/exePhase4: undefined symbol: _ZN5caffe3NetIfEC1ERKSsNS_5PhaseEPKS1_

Many thanks your time and effort.

===========================Error information==============

Bye: /home//caffe-lstm/examples/deep-activity-rec/exePhase1_2
========================
Phase 2 - B - Creating Mean File of Fused Data
Computing image mean for dataset:  trainval
------------------------------------------------------
Phase 3 - Generarting LSTM 2 Data - /home//caffe-lstm/examples/deep-activity-rec/ibrahim16-cvpr-simple/p4-network2
E0223 16:10:40.846400 18587 exePhase3.cpp:346] Make sure to have LD_LIBRARY_PATH pointing to LSTM implementation in case of LSTM

E0223 16:10:40.846997 18587 exePhase3.cpp:166] Fusing style = max_pool_players_2

E0223 16:10:40.847025 18587 exePhase3.cpp:169] frames_window = 10
E0223 16:10:40.847039 18587 exePhase3.cpp:171] Expected batch size = 120
E0223 16:10:40.847057 18587 exePhase3.cpp:178] Using GPU
E0223 16:10:40.847069 18587 exePhase3.cpp:179] Using Device_id=0
E0223 16:10:41.380697 18587 exePhase3.cpp:191] Model: /home/caffe-lstm/examples/deep-activity-rec/ibrahim16-cvpr-simple/p1-network1/z_snapshot_iter_1.caffemodel
E0223 16:10:41.380736 18587 exePhase3.cpp:192] Proto: /home/caffe-lstm/examples/deep-activity-rec/ibrahim16-cvpr-simple/p3-extract-features-networks/trainval.prototxt
E0223 16:10:41.380744 18587 exePhase3.cpp:194] Creating the test network
/home/caffe-lstm/examples/deep-activity-rec/exePhase3: symbol lookup error: /home/caffe-lstm/examples/deep-activity-rec/exePhase3: undefined symbol: _ZN5caffe3NetIfEC1ERKSsNS_5PhaseEPKS1_
------------------------------------------------------
Phase 4 - A - LSTM 2 Training - /hom/caffe-lstm/examples/deep-activity-rec/ibrahim16-cvpr-simple/p4-network2
Running Caffe using GPU In Directory  examples/deep-activity-rec/ibrahim16-cvpr-simple/p4-network2
========================
Phase 4 - B - Temporal Evaluation
E0223 16:10:52.527803 18610 exePhase4.cpp:252] Make sure to have LD_LIBRARY_PATH pointing to LSTM implementation in case of LSTM

E0223 16:10:52.528115 18610 exePhase4.cpp:146] Temporal Window = 10
E0223 16:10:52.528131 18610 exePhase4.cpp:153] Using GPU
E0223 16:10:52.528137 18610 exePhase4.cpp:154] Using Device_id = 0
E0223 16:10:52.913058 18610 exePhase4.cpp:166] Model: examples/deep-activity-rec/ibrahim16-cvpr-simple/p4-network2/z_snapshot_iter_2.caffemodel
E0223 16:10:52.913091 18610 exePhase4.cpp:167] Proto: examples/deep-activity-rec/ibrahim16-cvpr-simple/p4-network2/trainval-test-window-evaluation-network.prototxt
E0223 16:10:52.913099 18610 exePhase4.cpp:169] Creating the test network
examples/deep-activity-rec/exePhase4: symbol lookup error: examples/deep-activity-rec/exePhase4: undefined symbol: _ZN5caffe3NetIfEC1ERKSsNS_5PhaseEPKS1_
------------------------------------------------------

**Comment by hejiaoyu** [comment]
Hi Mostafa,
     When I ran ./script-simple.sh, I could not find z_snapshot_iter_1.caffemodel. How could I solve this problem? Look forward your reply. Thanks!

**Comment by qdinfish** [comment]
[z_log_dataset_net2.txt](https://github.com/mostafa-saad/deep-activity-rec/files/805762/z_log_dataset_net2.txt)
[z_trainval-test-log.txt](https://github.com/mostafa-saad/deep-activity-rec/files/805763/z_trainval-test-log.txt)

I think I fix all globe issues, but it still have errors .

**Comment by mostafa-saad** [comment]
Now you moved to a problem on my side. I still can't solve. I will put few hours this week on hope to solve it. It is a makefile problem. See some clarifications here: https://github.com/mostafa-saad/deep-activity-rec/issues/2

Specifically, I am not good in writing makefiles. When I put the project in eclipse, it works well. But using my makefile, fails in the 3rd phase.

**Comment by beibeirory** [comment]
Can you tell me how did you fix your problem about the missing libcaffe.so? @jichaoliu

**Comment by mostafa-saad** [comment]
@beibeirory 
https://github.com/mostafa-saad/deep-activity-rec/issues/2#issuecomment-283191286

**Comment by beibeirory** [comment]
I can get three EXEs. But when I run the script_simple.sh, I get the error about the missing libcaffe.so. By the way, I successfully compile the caffe-lstm. @mostafa-saad

**Comment by mostafa-saad** [comment]
I am not sure about this libcaffe.so. I think it is not about my project, but your run environment. You need to add the library directory to some path. Google the error
